# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u57ce\u5e02\u540d')),
                ('desc', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u673a\u6784\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u673a\u6784\u63cf\u8ff0')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('image', models.ImageField(upload_to='org/%Y%m', verbose_name='\u5c01\u9762\u56fe')),
                ('address', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('catgory', models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gr', '\u4e2a\u4eba'), ('school', '\u9ad8\u6821')], default='school', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b')),
                ('student_nums', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570')),
                ('course_nums', models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570')),
                ('tag', models.CharField(default='\u77e5\u540d\u9ad8\u6821', max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgnizations.City', verbose_name='\u6240\u5728\u57ce\u5e02')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u673a\u6784',
                'verbose_name_plural': '\u8bfe\u7a0b\u673a\u6784',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u6559\u5e08\u540d')),
                ('work_years', models.IntegerField(default=0, verbose_name='\u5de5\u4f5c\u5e74\u9650')),
                ('work_company', models.CharField(max_length=50, verbose_name='\u5de5\u4f5c\u5355\u4f4d')),
                ('work_position', models.CharField(max_length=50, verbose_name='\u5de5\u4f5c\u804c\u4f4d')),
                ('points', models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('image', models.ImageField(default='', upload_to='teachers/%Y/%m', verbose_name='\u6559\u5e08\u5934\u50cf')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgnizations.CourseOrg', verbose_name='\u6240\u5c5e\u673a\u6784')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08',
            },
        ),
    ]
